### ISSUE TITLE
Installation/registration impossible

### ISSUE THREAD

**Issue by Torsten-K** [surveybuilderteams/WebPress#3]
Hi,

I ran into two issues trying to get WebPress v1.3.1 up and running.

1)
Warning: Trying to access array offset on value of type null in /var/www[…]/html/[…]/webpress/header.php on line 186

2)
The captcha code is invisibe, so I can’t solve it. Registration impossible.

Too bad, I was so curious about this CMS.

**Comment by surveybuilder-admin** [comment]
I have fixed that update, thanks for the report

**Comment by Torsten-K** [comment]
Thank you for your quick reply and for your effort, @surveybuilder-admin, the error messages are gone.

But I still cannot see anything in the captcha. I can’t enable the GD extension, this is handled by my web hoster only. Anyway, I will try a local installation, but this might take a few days, as I am a bit busy at the moment.
Maybe it would be a quick solution, if I could disable the captcha, as WebPress only runs on my secured testing website, but how? Putting _captcha -> active_ to _false_ in _config.dat. json_ did not have any effect.

Best,
Torsten

**Comment by surveybuilder-admin** [comment]
@Torsten-K, it should be all fixed now GD is not required anymore.

**Comment by Torsten-K** [comment]
Ah, good, the captcha is gone. 
But I still cannot register. After filling out all those fields, the register button is still inactive. As email address I tried torsten @ webpress.com, only torsten or my own address, but it didn’t activate the green button.

![webpress-impossible-to-register](https://user-images.githubusercontent.com/806012/206919542-4be23c50-90f4-45a9-8d46-61cd914d3fca.png)

**Comment by surveybuilder-admin** [comment]
Password must match the following requirements
1 uppercase, 1 lowercase, 1 number, and 8 characters long. I have it set it into the hover of the textbox

**Comment by surveybuilder-admin** [comment]
@Torsten-K it has now been fixed, but really thanks for helping me out with these problems, I don't have a lot of eyes to catch every problem, but have extra pairs is really helping out.

**Comment by Torsten-K** [comment]
Yeah, it works now, I could create an account and log in. I’m glad I could help with my issue reports.

There are two error messages on top, but the errors don’t seem to break anything (I only thought I should tell you):

_Deprecated: stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/[…]/html/[…]/webpress/libs/users.lib.php on line 235

Deprecated: md5(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/[…]/html/[…]/webpress/libs/users.lib.php on line 239_

**Comment by surveybuilder-admin** [comment]
are you able to screenshot it

**Comment by Torsten-K** [comment]
![webpress-deprecated](https://user-images.githubusercontent.com/806012/206924702-5884a725-82d1-46c1-ab5a-4c5b221f14b0.png)

**Comment by surveybuilder-admin** [comment]
uninstall and download this one

**Comment by Torsten-K** [comment]
What should I download?

**Comment by surveybuilder-admin** [comment]
Nice, make sure you copy the private key, you are going to need that for IP changes or any tempted logon

**Comment by surveybuilder-admin** [comment]
@Torsten-K  
# What should I download?
I didn't see any message

**Comment by Torsten-K** [comment]
> @Torsten-K `What should I download?` I didn't see any message

No, just forget it. You wrote `uninstall and download this one, does it work?` before you had uploaded the new version, so I was wondering, but then deleted this question later.

**Comment by Torsten-K** [comment]
> make sure you copy the private key

Private key? What private key? Where did it show up anyway?

**Comment by surveybuilder-admin** [comment]
In the profile page

**Comment by surveybuilder-admin** [comment]
I am also working on a **blog page** and a block editor for next updates.

**Comment by Torsten-K** [comment]
> In the profile page

Okay, understood. Only for admins, as far as I can see.

---

> am also working on a **blog page** and a **block editor** for next updates. here is the viewer for the **blog plugin**

Good idea!

---

> Do you have a URL for that or is it running on a local server, because I want to see what it looks like on another users end

Running on web server in restricted area at the moment, but I can install it in a public area. Give me a few days, as I have other stuff to do at the moment. Thanks for your patience.

**Comment by surveybuilder-admin** [comment]
No problem, for some reason the **Online** plugin isn't counting every active user, I am going to try to fix it, but its not be helpful. Thanks for the long time support!

**Comment by surveybuilder-admin** [comment]
Block editor is being worked on

![Block Editor](https://user-images.githubusercontent.com/64079569/207587871-ef68964e-67bb-4f42-b833-e3e467deac3b.png)
